//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.AdminServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdminData", Namespace="http://schemas.datacontract.org/2004/07/CourierManagementSystem")]
    [System.SerializableAttribute()]
    public partial class AdminData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int courier_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dest_cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> employee_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sender_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int courier_id {
            get {
                return this.courier_idField;
            }
            set {
                if ((this.courier_idField.Equals(value) != true)) {
                    this.courier_idField = value;
                    this.RaisePropertyChanged("courier_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dest_city {
            get {
                return this.dest_cityField;
            }
            set {
                if ((object.ReferenceEquals(this.dest_cityField, value) != true)) {
                    this.dest_cityField = value;
                    this.RaisePropertyChanged("dest_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> employee_id {
            get {
                return this.employee_idField;
            }
            set {
                if ((this.employee_idField.Equals(value) != true)) {
                    this.employee_idField = value;
                    this.RaisePropertyChanged("employee_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string receiver_address {
            get {
                return this.receiver_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_addressField, value) != true)) {
                    this.receiver_addressField = value;
                    this.RaisePropertyChanged("receiver_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string receiver_name {
            get {
                return this.receiver_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_nameField, value) != true)) {
                    this.receiver_nameField = value;
                    this.RaisePropertyChanged("receiver_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sender_id {
            get {
                return this.sender_idField;
            }
            set {
                if ((this.sender_idField.Equals(value) != true)) {
                    this.sender_idField = value;
                    this.RaisePropertyChanged("sender_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminServiceReference.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/getData", ReplyAction="http://tempuri.org/IAdminService/getDataResponse")]
        Client.AdminServiceReference.AdminData[] getData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/getData", ReplyAction="http://tempuri.org/IAdminService/getDataResponse")]
        System.Threading.Tasks.Task<Client.AdminServiceReference.AdminData[]> getDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/assigndeliveryperson", ReplyAction="http://tempuri.org/IAdminService/assigndeliverypersonResponse")]
        void assigndeliveryperson(int courier_id, int employee_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/assigndeliveryperson", ReplyAction="http://tempuri.org/IAdminService/assigndeliverypersonResponse")]
        System.Threading.Tasks.Task assigndeliverypersonAsync(int courier_id, int employee_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/changestatus", ReplyAction="http://tempuri.org/IAdminService/changestatusResponse")]
        void changestatus(int courier_id, string new_status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/changestatus", ReplyAction="http://tempuri.org/IAdminService/changestatusResponse")]
        System.Threading.Tasks.Task changestatusAsync(int courier_id, string new_status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/getEmployeeList", ReplyAction="http://tempuri.org/IAdminService/getEmployeeListResponse")]
        int[] getEmployeeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/getEmployeeList", ReplyAction="http://tempuri.org/IAdminService/getEmployeeListResponse")]
        System.Threading.Tasks.Task<int[]> getEmployeeListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : Client.AdminServiceReference.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<Client.AdminServiceReference.IAdminService>, Client.AdminServiceReference.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.AdminServiceReference.AdminData[] getData() {
            return base.Channel.getData();
        }
        
        public System.Threading.Tasks.Task<Client.AdminServiceReference.AdminData[]> getDataAsync() {
            return base.Channel.getDataAsync();
        }
        
        public void assigndeliveryperson(int courier_id, int employee_id) {
            base.Channel.assigndeliveryperson(courier_id, employee_id);
        }
        
        public System.Threading.Tasks.Task assigndeliverypersonAsync(int courier_id, int employee_id) {
            return base.Channel.assigndeliverypersonAsync(courier_id, employee_id);
        }
        
        public void changestatus(int courier_id, string new_status) {
            base.Channel.changestatus(courier_id, new_status);
        }
        
        public System.Threading.Tasks.Task changestatusAsync(int courier_id, string new_status) {
            return base.Channel.changestatusAsync(courier_id, new_status);
        }
        
        public int[] getEmployeeList() {
            return base.Channel.getEmployeeList();
        }
        
        public System.Threading.Tasks.Task<int[]> getEmployeeListAsync() {
            return base.Channel.getEmployeeListAsync();
        }
    }
}
