//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ProfileServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profile", Namespace="http://schemas.datacontract.org/2004/07/CourierManagementSystem")]
    [System.SerializableAttribute()]
    public partial class Profile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ProfileServiceReference.History[] historyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.ProfileServiceReference.History[] history {
            get {
                return this.historyField;
            }
            set {
                if ((object.ReferenceEquals(this.historyField, value) != true)) {
                    this.historyField = value;
                    this.RaisePropertyChanged("history");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                if ((object.ReferenceEquals(this.mobileField, value) != true)) {
                    this.mobileField = value;
                    this.RaisePropertyChanged("mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_name {
            get {
                return this.user_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.user_nameField, value) != true)) {
                    this.user_nameField = value;
                    this.RaisePropertyChanged("user_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="History", Namespace="http://schemas.datacontract.org/2004/07/CourierManagementSystem")]
    [System.SerializableAttribute()]
    public partial class History : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int courier_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime date_of_orderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dest_cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sender_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string src_cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int courier_id {
            get {
                return this.courier_idField;
            }
            set {
                if ((this.courier_idField.Equals(value) != true)) {
                    this.courier_idField = value;
                    this.RaisePropertyChanged("courier_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_of_order {
            get {
                return this.date_of_orderField;
            }
            set {
                if ((this.date_of_orderField.Equals(value) != true)) {
                    this.date_of_orderField = value;
                    this.RaisePropertyChanged("date_of_order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dest_city {
            get {
                return this.dest_cityField;
            }
            set {
                if ((object.ReferenceEquals(this.dest_cityField, value) != true)) {
                    this.dest_cityField = value;
                    this.RaisePropertyChanged("dest_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string receiver_address {
            get {
                return this.receiver_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_addressField, value) != true)) {
                    this.receiver_addressField = value;
                    this.RaisePropertyChanged("receiver_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string receiver_mobile {
            get {
                return this.receiver_mobileField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_mobileField, value) != true)) {
                    this.receiver_mobileField = value;
                    this.RaisePropertyChanged("receiver_mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string receiver_name {
            get {
                return this.receiver_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_nameField, value) != true)) {
                    this.receiver_nameField = value;
                    this.RaisePropertyChanged("receiver_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sender_address {
            get {
                return this.sender_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.sender_addressField, value) != true)) {
                    this.sender_addressField = value;
                    this.RaisePropertyChanged("sender_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string src_city {
            get {
                return this.src_cityField;
            }
            set {
                if ((object.ReferenceEquals(this.src_cityField, value) != true)) {
                    this.src_cityField = value;
                    this.RaisePropertyChanged("src_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileServiceReference.IProfileService")]
    public interface IProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/getData", ReplyAction="http://tempuri.org/IProfileService/getDataResponse")]
        Client.ProfileServiceReference.Profile getData(int user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/getData", ReplyAction="http://tempuri.org/IProfileService/getDataResponse")]
        System.Threading.Tasks.Task<Client.ProfileServiceReference.Profile> getDataAsync(int user_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileServiceChannel : Client.ProfileServiceReference.IProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileServiceClient : System.ServiceModel.ClientBase<Client.ProfileServiceReference.IProfileService>, Client.ProfileServiceReference.IProfileService {
        
        public ProfileServiceClient() {
        }
        
        public ProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.ProfileServiceReference.Profile getData(int user_id) {
            return base.Channel.getData(user_id);
        }
        
        public System.Threading.Tasks.Task<Client.ProfileServiceReference.Profile> getDataAsync(int user_id) {
            return base.Channel.getDataAsync(user_id);
        }
    }
}
